server:
  port: 8000
spring:
  application:
    name: pie-monitor
  cloud:
    consul:
      port: 8500
      discovery:
        hostname: localhost
        serviceName: ${spring.application.name} # 注册到consul的服务名称
# 开放健康检查接口
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
