server:
  port: 8020
spring:
  application:
    name: pie-config
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        hostname: localhost
        serviceName: ${spring.application.name} # 注册到consul的服务名称
    config:
      label: master
      server:
        git:
          uri: https://github.com/409070933/pie.git  # 配置git仓库的地址
          search-paths: src/config-repo # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: 409070933@qq.com    # git仓库的账号
          password: gujianglong1209  # git仓库的密码