server:
  port: 8085
spring:
  application:
    name: pie-consumer
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        hostname: localhost
        serviceName: ${spring.application.name} # 注册到consul的服务名称
  boot:
    admin:
      client:
        url: "http://localhost:8000"
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1 #样本采集量，默认0.1
# 开放健康检查接口
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
#开启熔断器
feign:
  hystrix:
    enabled: true